build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: james_forbes@live.co.uk
    repo: plugins/drone-docker
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: james_forbes@live.co.uk
    repo: plugins/drone-docker
    tag: develop
    when:
      branch: develop

plugin:
  name: Docker
  desc: Build and publish images to a Docker registry
  type: publish
  image: plugins/drone-docker
  labels:
    - docker
    - image
    - container
